# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21.8
	yarn_mappings=1.21.8+build.1
	loader_version=0.16.14
	loom_version=1.11-SNAPSHOT

# Mod Properties
	mod_version=2.7.2+1.21.5
	mod_id=reinfbarrel
	maven_group=atonkish.reinfbarrel
	archives_base_name=reinforced-barrels

# Dependencies
	fabric_version=0.129.0+1.21.8
	reinforced_core_version=4.0.7+1.21.8

# Distribution platform
	curseforge_id=529875
	modrinth_id=Tx85779b
