name: publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish:
    runs-on: ubuntu-22.04
    env:
      JAVA_VERSION: 21
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: checkout mcmod repository
        uses: actions/checkout@v4
        with:
          repository: Aton-Kish/mcmod
          ref: maven
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: build/maven
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "microsoft"
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew publish
      - name: push to mcmod repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: build/maven
          destination-github-username: Aton-Kish
          destination-repository-name: mcmod
          user-email: 38515249+Aton-Kish@users.noreply.github.com
          target-branch: maven
